### ISSUE TITLE
microstache-1.0.2.2 doesn't compile with parsec-3.1.16.0

### ISSUE THREAD

**Issue by andreabedini** [haskellari/microstache#36]
parsec-3.1.16.0 has added `tokens'` and `string'` combinators which clash with microstache own definitions.

```
src/Text/Microstache/Parser.hs:65:27: error:
    Ambiguous occurrence ‘string'’
    It could refer to
       either ‘Text.Parsec.string'’,
              imported from ‘Text.Parsec’ at src/Text/Microstache/Parser.hs:27:1-43
              (and originally defined in ‘Text.Parsec.Char’)
           or ‘Text.Microstache.Parser.string'’,
              defined at src/Text/Microstache/Parser.hs:202:1
   |
65 |   (void . notFollowedBy . string') start
   |                           ^^^^^^^
```

A revision should be enough to fix this.

**Comment by phadej** [comment]
I made a revisions. Will make a release supporting `parsec-3.1.16.0` soon

**Comment by phadej** [comment]
https://hackage.haskell.org/package/microstache-1.0.2.3 is on Hackage, thanks for the report.

**Comment by andreabedini** [comment]
Fantastic, thanks @phadej  <3
